<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="mavdesk" failures="1" tests="3" name="Error Validations Test" time="9.111" errors="0" timestamp="2025-08-18T20:50:52 IST">
  <testcase classname="harshsingh.tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.392">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="harshsingh.tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.323">
    <failure type="java.lang.AssertionError" message="expected [] but found [Epic sadface:  and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Epic sadface:  and password do not match any user in this service]
at harshsingh.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="harshsingh.tests.ErrorValidationsTest" name="ProductErrorValidation" time="0.78"/>
</testsuite> <!-- Error Validations Test -->
